import { Component } from '@angular/core'; import { Router } from '@angular/router';
import { IonHeader,IonToolbar,IonButtons,IonBackButton,IonTitle,IonContent,IonItem,IonLabel,IonInput,IonTextarea,IonRadioGroup,IonRadio,IonButton } from '@ionic/angular/standalone'; import { FormsModule } from '@angular/forms'; import { CurrencyPipe,NgIf,NgFor } from '@angular/common'; import { FirebaseService,CartItem } from './firebase.service';
@Component({selector:'app-checkout',standalone:true,imports:[IonHeader,IonToolbar,IonButtons,IonBackButton,IonTitle,IonContent,IonItem,IonLabel,IonInput,IonTextarea,IonRadioGroup,IonRadio,IonButton,FormsModule,CurrencyPipe,NgIf,NgFor],template:`
<ion-header class="cc-header"><ion-toolbar><ion-buttons slot="start"><ion-back-button defaultHref="/cart"></ion-back-button></ion-buttons><ion-title>Checkout</ion-title></ion-toolbar></ion-header><ion-content><div class="page-pad">
<section class="checkout-card"><h2>Customer Details</h2><ion-item><ion-input label="Full name" labelPlacement="stacked" [(ngModel)]="customer.name"></ion-input></ion-item><ion-item><ion-input label="Phone" labelPlacement="stacked" [(ngModel)]="customer.phone"></ion-input></ion-item><ion-item><ion-input type="email" label="Email" labelPlacement="stacked" [(ngModel)]="customer.email"></ion-input></ion-item><ion-item *ngIf="fulfillment==='delivery'"><ion-textarea label="Delivery address" labelPlacement="stacked" [(ngModel)]="customer.address"></ion-textarea></ion-item></section>
<section class="checkout-card"><h2>Fulfillment</h2><ion-radio-group [(ngModel)]="fulfillment"><ion-item><ion-radio value="delivery">Delivery</ion-radio></ion-item><ion-item><ion-radio value="pickup">Store Pickup</ion-radio></ion-item></ion-radio-group></section>
<section class="checkout-card"><h2>Payment</h2><ion-radio-group [(ngModel)]="payment"><ion-item><ion-radio value="GCash">GCash</ion-radio></ion-item><ion-item><ion-radio value="GoTyme">GoTyme</ion-radio></ion-item><ion-item><ion-radio value="MariBank">MariBank</ion-radio></ion-item><ion-item><ion-radio value="Cash">Cash on {{fulfillment==='pickup'?'pickup':'delivery'}}</ion-radio></ion-item></ion-radio-group><img *ngIf="payment!=='Cash'" class="qr" [src]="'assets/images/qr-'+payment.toLowerCase()+'.png'"/></section>
<div class="summary" *ngIf="cart.length"><div><span>Subtotal</span><b>{{subtotal|currency:'PHP':'symbol':'1.0-0'}}</b></div><div><span>Delivery fee</span><b>{{delivery|currency:'PHP':'symbol':'1.0-0'}}</b></div><hr><div class="total"><span>Total</span><b>{{total|currency:'PHP':'symbol':'1.0-0'}}</b></div><ion-button expand="block" (click)="placeOrder()" [disabled]="placing">{{placing?'Placing order...':'Place Order'}}</ion-button></div></div></ion-content>`})
export class CheckoutPage {
  cart:CartItem[]=[]; deliveryFee=60; customer={name:'',phone:'',email:'',address:''}; fulfillment='delivery'; payment='GCash'; placing=false;
  constructor(private fb:FirebaseService,private router:Router){this.cart=this.fb.cart$.value; this.fb.deliveryFee$.subscribe(v=>this.deliveryFee=v); this.fb.user$.subscribe(async u=>{if(u&&!u.isAnonymous){this.customer.email=u.email||''; this.customer.name=u.displayName||''; const p=await this.fb.getProfile(u.uid); if(p){this.customer.name=p['fullName']||this.customer.name;this.customer.phone=p['phone']||'';}}});}
  get subtotal(){return this.cart.reduce((n,i)=>n+i.qty*i.unitPrice,0);} get delivery(){return this.fulfillment==='delivery'&&this.subtotal>0?this.deliveryFee:0;} get total(){return this.subtotal+this.delivery;}
  async placeOrder(){if(!this.cart.length)return; if(!this.customer.name||!this.customer.phone||(this.fulfillment==='delivery'&&!this.customer.address)){alert('Please fill in the required customer details.');return;} this.placing=true; try{const items=this.cart.map(i=>({id:i.id,name:i.name,price:i.unitPrice,qty:i.qty,size:i.selectedSize||null})); const id=await this.fb.createOrder({items,totals:{subtotal:this.subtotal,deliveryFee:this.delivery,total:this.total},fulfillment:this.fulfillment,customer:this.customer,paymentMethod:this.payment}); alert('Order placed successfully! Order ID: #CC-'+id.slice(0,6).toUpperCase()); this.router.navigateByUrl('/transactions');}catch(e){console.error(e);alert('Could not place the order. Please try again.');}finally{this.placing=false;}}
}
