import { Component } from '@angular/core';
import { IonHeader,IonToolbar,IonButtons,IonButton,IonIcon,IonContent,IonSearchbar,IonCard,IonCardContent } from '@ionic/angular/standalone';
import { Router } from '@angular/router'; import { addIcons } from 'ionicons'; import { personCircleOutline, cartOutline, arrowForward, sparklesOutline } from 'ionicons/icons';
import { FirebaseService,Product } from './firebase.service'; import { ProductCardComponent } from './product-card.component'; import { AsyncPipe,NgFor } from '@angular/common';
@Component({selector:'app-home',standalone:true,imports:[IonHeader,IonToolbar,IonButtons,IonButton,IonIcon,IonContent,IonSearchbar,IonCard,IonCardContent,ProductCardComponent,AsyncPipe,NgFor],template:`
<ion-header class="cc-header"><ion-toolbar><img src="assets/images/logo-mark.png" class="logo" slot="start"><ion-buttons slot="end"><ion-button (click)="go('/auth')"><ion-icon slot="icon-only" name="person-circle-outline"></ion-icon></ion-button><ion-button (click)="go('/cart')"><ion-icon slot="icon-only" name="cart-outline"></ion-icon></ion-button></ion-buttons></ion-toolbar></ion-header>
<ion-content [fullscreen]="true"><div class="home-wrap">
<div class="welcome">GOOD MORNING ☕</div>
<section class="hero-mobile"><img src="assets/images/hero-banner.jpg"><div class="hero-overlay"><span>Handcrafted daily</span><h1>Freshly Brewed <em>Comfort</em> in Every Sip & Bite</h1><p>Coffee, pastries, and little things worth taking home.</p><ion-button (click)="go('/menu')">Order Now <ion-icon slot="end" name="arrow-forward"></ion-icon></ion-button></div></section>
<section class="section"><div class="section-title"><div><small>WHAT WE MAKE</small><h2>Three crafts, one counter</h2></div></div><div class="quick-grid"><button (click)="go('/menu?cat=Coffee')">☕<span>Coffee</span></button><button (click)="go('/menu?cat=Pastries')">🥐<span>Pastries</span></button><button (click)="go('/menu?cat=Accessories')">👜<span>Merch</span></button></div></section>
<section class="brew-card"><img src="assets/images/espresso-pic.jpg"><div><small>BREWED TO PERFECTION</small><h2>Great coffee isn't rushed.</h2><p>Carefully sourced beans, small-batch roasting, and a little patience in every cup.</p><ion-button fill="clear" (click)="go('/info/about')">Our Story <ion-icon slot="end" name="arrow-forward"></ion-icon></ion-button></div></section>
<section class="section"><div class="section-title"><div><small>LOVED BY REGULARS</small><h2>Popular this week</h2></div><ion-button fill="clear" (click)="go('/menu')">See all</ion-button></div><div class="horizontal"><app-product-card *ngFor="let p of popular|async" [product]="p"></app-product-card></div></section>
<section class="story-card"><img src="assets/images/ourstory.png"><div><small>OUR STORY</small><h2>From a class requirement to our first real café.</h2><p>What started as a college project kept growing because we loved where it was going.</p><ion-button fill="outline" (click)="go('/info/about')">About Us</ion-button></div></section>
</div></ion-content>`})
export class HomePage { popular=this.fb.products$.pipe(); constructor(private fb:FirebaseService,private router:Router){addIcons({personCircleOutline,cartOutline,arrowForward,sparklesOutline});} go(url:string){this.router.navigateByUrl(url);} }
